version: "3"

services:
  os-ticket:
    container_name: os-ticket
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:80"
    networks:
      - docker-network
    restart: always 
networks:
  docker-network:
    driver: bridge